baseURL: "/"
theme: "up-business-theme"


title: "CBC"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "CBC"
  description: "Cross Border China (CBC) can help you to overcome your business challenges and accompany you during your (first) steps in Europe, starting from the Netherlands."
  images: 
    - "images/hero-image.png"



  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
   

  contact:
    - " jeremy@crossborderchina.nl"
    

  copyright: "© 2023 cross-border-china All Rights Reserved"

taxonomies:
  series: "series"
  tags: "tags"


DefaultContentLanguage: ch

defaultContentLanguageInSubdir: true

languages:
  en:
    title: Cross Border China
    languageName: Eng
    weight: 1
    contentDir: "content/en"
    menus:
        main:
           - name: "Home"
             url: "/#hero"
             weight: 1

           - name: "Services"
             url: "/services"
             weight: 2
          
           - name: "About"
             url: "/about"
             weight: 3

           - name: "Team"
             url: "/team"
             weight: 4

           - name: "Contact"
             url: "/contact"
             weight: 5

          #  - name: "Blog"
          #    url: "/blog"
          #    weight: 5
          
        buttons:
            - name: "Get a quote"
              url: "/contact"
              weight: 5
              pre: "btn btn-primary text-light"

        
        footer:
           - name: "Home"
             url: "/"
             weight: 1

           - name: "Services"
             url: "/services"
             weight: 2

           - name: "How we work"
             url: "/about"
             weight: 3

           - name: "Our team"
             url: "/team"
             weight: 4
  
           - name: "Contact"
             url: "/contact"
             weight: 5

          #  - name: "Blog"
          #    url: "/blog"
          #    weight: 5
    
  ch:
    title: Cross Border China
    languageName: ch
    weight: 2
    contentDir: "content/ch"
    menus:
        main:
           - name: "家"
             url: "/"
             weight: 1

           - name: "服务"
             url: "/services"
             weight: 2
          
           - name: "关于"
             url: "/about"
             weight: 3

           - name: "团队"
             url: "/team"
             weight: 4

           - name: "接触"
             url: "/contact"
             weight: 5

          #  - name: "博客"
          #    url: "/blog"
          #    weight: 5

        buttons:
            - name: " 获取报价"
              url: "/contact"
              weight: 5
              pre: "btn btn-primary text-light"

        footer:
           - name:  "家"
             url: "/"
             weight: 1

           - name: "服务"
             url: "/services"
             weight: 2

           - name:  "关于"
             url: "/about"
             weight: 3

           - name: "团队"
             url: "/team"
             weight: 4
  
           - name: "接触"
             url: "/contact"
             weight: 5

        


